name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: 8
          cache: "gradle"
      
      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew setupCiWorkspace
          ./gradlew build

      # 新增上传JAR文件的步骤，并在zip文件名中加入commit sha256
      - name: Zip JARs with commit SHA
        run: |
          mkdir -p build/artifacts
          zip build/artifacts/build-artifacts-${{ github.sha }}.zip build/libs/*.jar
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.sha }}
          path: build/artifacts/build-artifacts-${{ github.sha }}.zip
